### ISSUE TITLE
could not get maven resources from jitpack maven repository

### ISSUE THREAD

**Issue by BBSee** [namjug-kim/reactive-crypto#132]
- Expected behavior: get resources
- Actual behavior: could not
- Steps to reproduce:
- Exchange:
- Reactive Crypto version: 0.2.3
- JVM / Kotlin version: 1.8
- OS version:win 10

**Comment by namjug-kim** [comment]
please attach your maven pom.xml source. it will helpful for figure out problem

**Comment by BBSee** [comment]
> please attach your maven pom.xml source. it will helpful for figure out problem



> please attach your maven pom.xml source. it will helpful for figure out problem

OK,THX, I`v asked my friends to help me, they could not get resources neither with following pom labels:
`<dependency>
                <groupId>com.github.namjug-kim.reactive-crypto</groupId>
                <artifactId>reactive-crypto</artifactId>
                <version>0.2.3.RELEASE</version>
            </dependency>`
`<dependency>
                <groupId>com.github.namjug-kim.reactive-crypto</groupId>
                <artifactId>reactive-crypto</artifactId>
                <version>0.2.3.RELEASE</version>
            </dependency>`

In fact ,I cloud not get any RELEASE or SNAPSHOOT

**Comment by BBSee** [comment]
```xml
 	<dependency>
                <groupId>com.github.namjug-kim.reactive-crypto</groupId>
                <artifactId>reactive-crypto</artifactId>
                <version>0.2.3.RELEASE</version>
     </dependency>
      <repositories>
            <repository>
                <id>jitpack.io</id>
                <url>https://jitpack.io</url>
            </repository>
    </repositories>      
```

**Comment by namjug-kim** [comment]
@BBSee oh.. readme document was a little short :(. if you want use whole project change groupId to `com.github.namjug-kim` it will be work.

```
<dependency>
        <groupId>com.github.namjug-kim</groupId>
        <artifactId>reactive-crypto</artifactId>
        <version>0.2.3.RELEASE</version>
</dependency>
```

**Comment by BBSee** [comment]
> @BBSee oh.. readme document was a little short :(. if you want use whole project change groupId to `com.github.namjug-kim` it will be work.
> 
> ```
> <dependency>
>         <groupId>com.github.namjug-kim</groupId>
>         <artifactId>reactive-crypto</artifactId>
>         <version>0.2.3.RELEASE</version>
> </dependency>
> ```

Thank you very much,it is working now!  :)
